const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.NinePatch,
		C3.Behaviors.Timer,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Timeline,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.List,
		C3.Behaviors.Tween,
		C3.Plugins.sliderbar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Tilemap.Exps.TileToPositionX,
		C3.Plugins.Tilemap.Exps.TileToPositionY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.System.Exps.originalwindowheight,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.NinePatch.Exps.BBoxMidY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.NinePatch.Acts.ZMoveToObject,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.List.Exps.ItemTextAt,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Text.Acts.ChangeTags,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Exps.WheelDeltaY,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.Tags,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Exps.X,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Timeline.Cnds.OnAnyTimelineFinished,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.TextBox.Cnds.HasTags,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerAvatar,
		C3.Plugins.TextBox.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Eponesh_GameScore.Acts.ImagesUpload,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetAvatar,
		C3.Plugins.Eponesh_GameScore.Exps.ImagesResize,
		C3.Plugins.Eponesh_GameScore.Exps.ImagesCurImageSrc,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerLogin,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetName,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Acts.SetMaxLength,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.ScriptsInEvents.MenuEvents_Event107_Act2,
		C3.ScriptsInEvents.MenuEvents_Event108_Act1,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerLoginComplete,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerWaitForReady,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPlayerLoadComplete,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerLoad,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.sliderbar.Cnds.HasTags,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Tilemap.Acts.SetDefaultColor,
		C3.Plugins.TextBox.Acts.SetElemAttribute,
		C3.Plugins.Button.Acts.SetElemAttribute,
		C3.Plugins.sliderbar.Acts.SetElemAttribute,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Exps.XForID,
		C3.Plugins.Touch.Exps.YForID,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Timeline.Acts.PlayTimelineByName,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Sprite.Acts.SetAnimSpeed
	];
};
self.C3_JsPropNameTable = [
	{Mapa: 0},
	{ToX: 0},
	{ToY: 0},
	{OldX: 0},
	{OldY: 0},
	{Accent: 0},
	{Sausage: 0},
	{Grid: 0},
	{DragDrop: 0},
	{tv: 0},
	{note_margins: 0},
	{particles: 0},
	{bumper: 0},
	{bumper_text: 0},
	{index: 0},
	{conditions: 0},
	{command: 0},
	{controlpad: 0},
	{value: 0},
	{controlpad_text: 0},
	{insert_position: 0},
	{slider_axis: 0},
	{UPPER_LIMIT: 0},
	{LOWER_LIMIT: 0},
	{DELTA: 0},
	{TopY: 0},
	{BottomY: 0},
	{progress: 0},
	{slider: 0},
	{bumper_frame: 0},
	{base_color: 0},
	{confirm_color: 0},
	{confirm: 0},
	{Timer: 0},
	{execute_button: 0},
	{Pin: 0},
	{trashbin: 0},
	{tuturing: 0},
	{scale: 0},
	{origin_scale: 0},
	{scale_clicked: 0},
	{scale_hovered: 0},
	{Rotate: 0},
	{Sine: 0},
	{Fade: 0},
	{Manuscript: 0},
	{cursor: 0},
	{conditionpad: 0},
	{compass: 0},
	{is_clicked: 0},
	{on_color: 0},
	{off_color: 0},
	{condibutton: 0},
	{Input: 0},
	{Button: 0},
	{respect: 0},
	{Occitanian: 0},
	{is_opened: 0},
	{taskbutton: 0},
	{taskpad: 0},
	{timemachine: 0},
	{pointer: 0},
	{menu_button: 0},
	{tutorial_button: 0},
	{catsound: 0},
	{avatar: 0},
	{Accumulator: 0},
	{profile_input: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Timeline: 0},
	{Touch: 0},
	{Audio: 0},
	{Browser: 0},
	{AJAX: 0},
	{Storage: 0},
	{direction: 0},
	{direction_index: 0},
	{is_hit: 0},
	{is_win: 0},
	{Cat: 0},
	{ToAngle: 0},
	{arrow: 0},
	{Muse: 0},
	{Current: 0},
	{Queue: 0},
	{Directions: 0},
	{Condition: 0},
	{Badwords: 0},
	{Stats: 0},
	{Levelstars: 0},
	{Cycles: 0},
	{store_index: 0},
	{store_skin: 0},
	{choosen_index: 0},
	{choosen_skin: 0},
	{CatSkins: 0},
	{OwnedSkins: 0},
	{GameSkins: 0},
	{FADER: 0},
	{Say: 0},
	{Speed: 0},
	{sound: 0},
	{Aqum: 0},
	{GamePush: 0},
	{level_info: 0},
	{Tween: 0},
	{Coin: 0},
	{snow: 0},
	{SliderBar: 0},
	{Objects: 0},
	{Creatures: 0},
	{Gamebuttons: 0},
	{Accents: 0},
	{ICONSIZE: 0},
	{start_x: 0},
	{start_y: 0},
	{start_direction: 0},
	{sausages_cur: 0},
	{sausages_count: 0},
	{is_condipad_opened: 0},
	{command_count: 0},
	{sidebar_y: 0},
	{string_condition: 0},
	{cycle_tag: 0},
	{cycle_uid: 0},
	{COLOR_IF: 0},
	{COLOR_WHILE: 0},
	{COLOR_FOR: 0},
	{cycle: 0},
	{depth: 0},
	{deltaX: 0},
	{deltaY: 0},
	{check_dir: 0},
	{type: 0},
	{dirrection: 0},
	{wall: 0},
	{NewX: 0},
	{NewY: 0},
	{is_loaded: 0},
	{scroll_x: 0},
	{scroll_y: 0},
	{screen: 0},
	{tag: 0},
	{phase: 0},
	{cat_name: 0},
	{completed_levels: 0},
	{BG_ACCENT: 0},
	{BLUE_ACCENT: 0},
	{RED_ACCENT: 0},
	{Level: 0},
	{Unlock: 0},
	{IsBlocked: 0},
	{IsFading: 0},
	{DEBUG: 0},
	{Music: 0},
	{In: 0},
	{Out: 0},
	{Color: 0},
	{LAYOUT_MAX_SCALE: 0},
	{LAYOUT_MIN_SCALE: 0},
	{TouchPanID: 0},
	{TouchZoomID: 0},
	{TouchLastX: 0},
	{TouchLastY: 0},
	{InitialScale: 0},
	{TouchStartDistance: 0},
	{TouchCurrentDistance: 0},
	{TouchCurrentMidX: 0},
	{TouchCurrentMidY: 0},
	{star_index: 0},
	{mouse_phase: 0}
];

self.InstanceType = {
	Mapa: class extends self.ITilemapInstance {},
	Sausage: class extends self.ISpriteInstance {},
	Grid: class extends self.ITiledBackgroundInstance {},
	tv: class extends self.ISpriteInstance {},
	note_margins: class extends self.ITiledBackgroundInstance {},
	particles: class extends self.IParticlesInstance {},
	bumper: class extends self.ITiledBackgroundInstance {},
	bumper_text: class extends self.ITextInstance {},
	command: class extends self.ISpriteInstance {},
	controlpad: class extends self.IWorldInstance {},
	controlpad_text: class extends self.ITextInstance {},
	insert_position: class extends self.ISpriteInstance {},
	slider_axis: class extends self.ITiledBackgroundInstance {},
	slider: class extends self.ISpriteInstance {},
	bumper_frame: class extends self.ITiledBackgroundInstance {},
	execute_button: class extends self.ISpriteInstance {},
	trashbin: class extends self.ISpriteInstance {},
	tuturing: class extends self.ISpriteInstance {},
	Manuscript: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	conditionpad: class extends self.IWorldInstance {},
	compass: class extends self.ISpriteInstance {},
	condibutton: class extends self.ISpriteInstance {},
	Input: class extends self.ITextInputInstance {},
	Button: class extends self.IButtonInstance {},
	respect: class extends self.ISpriteInstance {},
	Occitanian: class extends self.ISpriteInstance {},
	taskbutton: class extends self.ISpriteInstance {},
	taskpad: class extends self.IWorldInstance {},
	timemachine: class extends self.ISpriteInstance {},
	pointer: class extends self.ISpriteInstance {},
	menu_button: class extends self.ISpriteInstance {},
	tutorial_button: class extends self.ISpriteInstance {},
	catsound: class extends self.ISpriteInstance {},
	avatar: class extends self.ISpriteInstance {},
	profile_input: class extends self.ITextInputInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Timeline: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Storage: class extends self.IInstance {},
	Cat: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	Muse: class extends self.ISpriteInstance {},
	Queue: class extends self.IArrayInstance {},
	Directions: class extends self.IArrayInstance {},
	Condition: class extends self.IArrayInstance {},
	Badwords: class extends self.IDictionaryInstance {},
	Stats: class extends self.IDictionaryInstance {},
	Levelstars: class extends self.IJSONInstance {},
	Cycles: class extends self.IDictionaryInstance {},
	CatSkins: class extends self.IArrayInstance {},
	OwnedSkins: class extends self.IJSONInstance {},
	GameSkins: class extends self.IArrayInstance {},
	FADER: class extends self.ITiledBackgroundInstance {},
	Aqum: class extends self.ITextInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	level_info: class extends self.IListInstance {},
	Coin: class extends self.ISpriteInstance {},
	snow: class extends self.IParticlesInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	Objects: class extends self.ISpriteInstance {},
	Creatures: class extends self.ISpriteInstance {},
	Gamebuttons: class extends self.ISpriteInstance {},
	Accents: class extends self.ISpriteInstance {}
}